---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

extends: "default"

rules:

  braces:
    max-spaces-inside: 1
    level: "error"

  brackets:
    max-spaces-inside: 1
    level: "error"

  # quoted-strings:
  #   quote-type: "any"
  #   required: true
...
