[tool.isort]
profile = "black"
src_paths = ["app", "tests"]

[tool.black]
# line_length = 88
src_paths = ["app", "tests"]
target-version = ["py37", "py38", "py39", "py310"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rfEX -svv --color=yes --code-highlight=yes --doctest-modules"
testpaths = [
    "tests"
]
log_format = "%(asctime)s %(levelname)s %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"

# https://pypi.org/project/interrogate/
[tool.interrogate]
fail-under = 95
exclude = ["setup.py", "docs", "build", "tests"]
# ignore-regex = ["^get$", "^mock_.*", ".*BaseClass.*"]
# possible values: 0 (minimal output), 1 (-v), 2 (-vv)
verbose = 0

# https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml
# https://mypy.readthedocs.io/en/stable/config_file.html#example-pyproject-toml
[tool.mypy]
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
warn_return_any = true

# [[tool.mypy.overrides]]
# module = 'mypy-pytest'
# ignore_missing_imports = true
